version: "3.9"
services:
  db:
    profiles:
      - dev
      - testing
    image: mongo:latest
    volumes:
      - mongo-data:/data/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword

  backend:
    profiles:
      - dev
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.backend
      target: dev
    environment:
      FLASK_DEBUG: 1
      DEV_LOGIN: 1
      FLASK_APP: form_manager
      TZ: Europe/Stockholm
    depends_on:
      - db
    restart: on-failure
    volumes:
      - type: bind
        source: ./form_manager
        target: /code/form_manager

  frontend:
    profiles:
      - dev
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.frontend
      target: dev
    restart: on-failure
    environment:
      VERSION: "dev"
    volumes:
      - type: bind
        source: ./frontend/src
        target: /code/src

  proxy:
    profiles:
      - dev
    image: nginxinc/nginx-unprivileged:alpine
    ports:
      - 127.0.0.1:5050:8080
    depends_on:
      - backend
      - frontend
      - db
    volumes:
      - type: bind
        source: ./Dockerfiles/nginx.conf.dev
        target: /etc/nginx/conf.d/default.conf

  test:
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.backend
      target: test
    environment:
      DEV_LOGIN: 1
    profiles:
      - testing
    depends_on:
      - db
    restart: "no"
    volumes:
      - type: bind
        source: ./test
        target: /code/test

  mailcatcher:
    profiles:
      - dev
    image: sj26/mailcatcher:latest
    ports:
      - 127.0.0.1:1080:1080

volumes:
  mongo-data: {}
