# syntax=docker/dockerfile:1

###############################################################################
#                               Base Image                                    #
###############################################################################
FROM node:22-slim AS base

# Sets default shell to `sh -exc`:
# -e  exit on error
# -x  write commands to standard error
# -c  read commands from the command_string operand
SHELL ["sh", "-exc"]

# Declare global bin directory for pnpm.
ENV PNPM_HOME="/pnpm"

# Add pnpm global bin directory to PATH.
ENV PATH="$PNPM_HOME:$PATH"

# Enable corepack to handle package managers.
#RUN npm install --global corepack@latest
RUN corepack enable pnpm

# Add Quasar CLI.
RUN pnpm add -g @quasar/cli

# Switch to application working directory.
WORKDIR /app

# Install dependencies without the application itself.
# This layer is cached until package.json or pnpm-lock.yaml change.
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    --mount=type=bind,source=frontend/package.json,target=package.json \
    --mount=type=bind,source=frontend/pnpm-lock.yaml,target=pnpm-lock.yaml \
    pnpm install --frozen-lockfile

# Copy project directory into build container.
COPY ./frontend /app


###############################################################################
#                              Build Stage                                    #
###############################################################################
FROM base AS build

# Define build-time variable and environment variable.
ARG version
ENV VERSION=$version

# Build Quasar application.
RUN quasar build \
    --mode spa \
    --dist-dir dist/spa


###############################################################################
#                         Runtime Stage - Production                          #
###############################################################################
FROM nginxinc/nginx-unprivileged:alpine AS production

COPY --from=build /app/dist/spa/ /usr/share/nginx/html/
COPY ./Dockerfiles/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
