###############################################
# Base Image
###############################################
FROM python:3.13-alpine AS base

RUN apk update && apk upgrade
RUN apk add gcc musl-dev libffi-dev
COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt
COPY ./form_manager /code/form_manager
WORKDIR /code/
ENV PYTHONPATH=/code


###############################################
# Development Image
###############################################
FROM base AS dev

CMD ["flask", "run", "-h", "0.0.0.0", "--port", "5000"]


###############################################
# Test Image
###############################################
FROM base AS test

RUN pip install pytest-cov
COPY ./test /code/test
CMD ["pytest", "test"]


###############################################
# Production Image
###############################################
FROM base AS production

# Create user to avoid running application as root
# TODO Test in dev first
ARG USER=form-manager
RUN useradd -u 1000 $USER
RUN chown -R $USER:$USER /home/$USER/
USER $USER

RUN pip install gunicorn
ENV GUNICORN_CMD_ARGS="--bind=0.0.0.0:8000 --workers=2 --thread=4 --worker-class=gthread --forwarded-allow-ips='*' --access-logfile -"
WORKDIR /code/form_manager
CMD ["gunicorn", "app:app"]
