###############################################
# Base Image
###############################################
# TODO 23 is the new LTS version
FROM node:18-alpine AS base

RUN yarn global add @quasar/cli

COPY ./frontend/package.json /package.json
COPY ./frontend/yarn.lock /yarn.lock
WORKDIR /
RUN yarn install

COPY ./frontend /code
RUN mv /node_modules /code/
WORKDIR /code


###############################################
# Builder Image
###############################################
FROM base AS build

ARG version
ENV VERSION=$version

RUN quasar build


###############################################
# Development Image
###############################################
FROM base AS dev

CMD ["quasar", "dev"]


###############################################
# Production Image
###############################################
FROM nginxinc/nginx-unprivileged:alpine AS production

# Create user to avoid running application as root
# TODO Test in dev first
ARG USER=form-manager
RUN useradd -u 1000 $USER
RUN chown -R $USER:$USER /home/$USER/
USER $USER

COPY --from=build /code/dist/spa/ /usr/share/nginx/html/
COPY ./Dockerfiles/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
