# This Dockerfile has been largely inspired by
# https://hynek.me/articles/docker-uv/

# syntax=docker/dockerfile:1

###############################################################################
#                                 Build Stage                                 #
###############################################################################
FROM python:3.13-slim AS build

# Sets default shell to `sh -exc`:
# -e  exit on error
# -x  write commands to standard error
# -c  read commands from the command_string operand
SHELL ["sh", "-exc"]

# Avoid interactive prompts during package operations.
ENV DEBIAN_FRONTEND=noninteractive

### Start build preparation -- this should be a separate build container for better reuse

# Copy `uv` from the third-party image into the build container
COPY --from=ghcr.io/astral-sh/uv:0.6.7 /uv /usr/local/bin/uv

# - Silence uv complaining about not being able to use hard links,
# - tell uv to byte-compile packages for faster application startups,
# - prevent uv from downloading isolated Python builds,
# - specify Python version (use `/usr/bin/python3.12` on uv 0.5.0 and later),
# - declare `/app` as the target for `uv sync`.
ENV UV_LINK_MODE=copy \
    UV_COMPILE_BYTECODE=1 \
    UV_PYTHON_DOWNLOADS=never \
    UV_PYTHON=python3.13 \
    UV_PROJECT_ENVIRONMENT=/app

### End build preparation -- this is where the app Dockerfile should start.


# Synchronise DEPENDENCIES without the application itself.
# This layer is cached until uv.lock or pyproject.toml change, which are only
# temporarily mounted into the build container since we don't need them in production.
RUN --mount=type=cache,target=/root/.cache \
    --mount=type=bind,source=src/form_manager/uv.lock,target=uv.lock \
    --mount=type=bind,source=src/form_manager/pyproject.toml,target=pyproject.toml \
    uv sync \
        --locked \
        --no-dev \
        --no-install-project


###############################################################################
#                                Runtime Stage                                #
###############################################################################
FROM python:3.13-slim AS runtime

# Sets default shell to `sh -exc`.
SHELL ["sh", "-exc"]

# Add application virtual environment to PATH and declare PYTHONPATH.
ENV PATH=/app/bin:$PATH \
    PYTHONPATH=/app

# Create non-root user and group `app`.
RUN groupadd -r app && \
    useradd -r -d /app -g app -N app

# Set entrypoint script and stop signal for the container.
# (see <https://hynek.me/articles/docker-signals/>)
ENTRYPOINT ["/docker-entrypoint.sh"]
STOPSIGNAL SIGINT

# Clean up package lists to reduce image size.
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copy entrypoint script into container and make it executable.
COPY Dockerfiles/entrypoint-backend.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Copy pre-built application directory and change ownership to `app` user and group.
COPY --from=build --chown=app:app /app /app

# Copy NON-PACKAGED application into runtime container.
COPY --chown=app:app ../src/form_manager/*.py /app/form_manager/

# Set user to `app` and working directory to `/app`
USER app
WORKDIR /app/form_manager
