---
name: Publish Docker Image
on:
  push:
    branches:
      - main
      - "more-concurrency"
  release:
    types: [published]
jobs:
  push_to_registry:
    if: github.repository == 'scilifelabdatacentre/form-manager'
    name: Publish Docker Image
    concurrency:
      group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}: ${{ matrix.dockerfile }}'
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfiles/Dockerfile.backend
            images: |
              ghcr.io/scilifelabdatacentre/form-manager-backend
          - dockerfile: Dockerfiles/Dockerfile.frontend
            images: |
              ghcr.io/scilifelabdatacentre/form-manager-frontend
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run setup-qemu-action
        uses: docker/setup-qemu-action@v2
      - name: Run docker/setup-buildx-action
        uses: docker/setup-buildx-action@v2
      - name: Log in to Github Container Repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.images }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and Publish
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          context: .
          push: true
          build-args: version=${{ github.ref_name }}
          target: production
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64 # the qemu and buildx steps can be skipped if arm is removed
